name: Deploy to Static Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment: github-pages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Debug secrets
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
      run: |
    [ "$github-pages" = qa ] && echo $VITE_SUPABASE_URL | base64 --decode > .env
    [ "$github-pages" = prod ] && echo $VITE_SUPABASE_KEY | base64 --decode > .env

    - name: Build project
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
